GET http://127.0.0.1:5000/api/users HTTP/1.1

###
GET http://127.0.0.1:5000/api/users/1 HTTP/1.1

###
GET http://127.0.0.1:5000/api/users/1/tasks HTTP/1.1

###
POST http://127.0.0.1:5000/api/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "User",
    "lastName": "Lastname",
    "email": "user1@gmail.com",
    "passwordHash": "1qazxsw2",
    "birthday": "2000-03-03"
}

###
GET http://127.0.0.1:5000/api/tasks HTTP/1.1